---
- name: Configure Incident Manager Server (GLPI)
  hosts: incident_manager
  become: yes
  tasks:
    - name: Corriger dpkg si nécessaire
      command: dpkg --configure -a
      become: yes
      ignore_errors: yes

    - name: Mettre à jour apt
      apt:
        update_cache: yes
      become: yes

    - name: Purger MySQL
      apt:
        name: mysql-server
        state: absent
        purge: yes
        force: yes
      become: yes

    - name: Supprimer les fichiers résiduels
      shell: |
        rm -rf /var/lib/mysql
        rm -rf /etc/mysql
      become: yes
      ignore_errors: true

    - name: Installer python3-pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install apt-utils
      ansible.builtin.apt:
        name: apt-utils
        state: present

    - name: Download and install GLPI
      get_url:
        url: https://github.com/glpi-project/glpi/archive/refs/tags/10.0.17.tar.gz
        dest: /tmp/glpi.tar.gz
      retries: 3
      delay: 15
      register: result
      until: result is success
    
    - name: Install Apache2
      apt:
        name:
          - apache2
          - mariadb-server
        state: present
        update_cache: yes
      become: yes

    - name: Extract GLPI archive
      unarchive:
        src: /tmp/glpi.tar.gz
        dest: /var/www/
        creates: /var/www/glpi
        remote_src: yes

    - name: Set correct permissions for GLPI
      file:
        path: /var/www/glpi
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Enable GLPI site
      command: a2ensite glpi.conf

    - name: Enable Apache rewrite module
      apache2_module:
        name: rewrite
        state: present

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted

##    - name: Start MariaDB Service
  #    command: /etc/init.d/mariadb start 

 #   - name: Create MariaDB Database for GLPI
  #    mysql_db:
 #       name: glpi
 #       state: present
  #      login_user: root
   #     login_password: root

 #   - name: Configure GLPI database in MySQL
 #     mysql_db:
 #       name: glpi
 #       state: present
 #       login_user: root
  #      login_password: root

#    - name: Install GLPI via web installer (manually)
#      uri:
#        url: http://localhost/glpi
#        method: GET
 #       status_code: 200
