---
- name: Configure Update Manager Server
  hosts: update_manager
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure unattended-upgrades is installed (for auto-updates)
      apt:
        name: unattended-upgrades
        state: present

    - name: Enable automatic updates
      lineinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: '^APT::Periodic::Update-Package-Lists'
        line: 'APT::Periodic::Update-Package-Lists "1";'

    - name: Ensure unattended-upgrades is enabled
      service:
        name: unattended-upgrades
        state: started
        enabled: yes

    - name: Configure APT for security updates
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^// Unattended-Upgrade::Allowed-Origins'
        line: 'Unattended-Upgrade::Allowed-Origins {
                "Ubuntu:$(lsb_release -c | awk "{print $2}")-security";
                "Debian:$(lsb_release -c | awk "{print $2}")-security";
            };'
      notify:
        - "Restart unattended-upgrades"

  handlers:
    - name: Restart unattended-upgrades
      service:
        name: unattended-upgrades
        state: restarted
